### ISSUE TITLE
@jeanlouisboudart: @highway-to-urhell asks you to fix your GitHub account!

### ISSUE THREAD

**Issue by npoirier-palo** [highway-to-urhell/people#1]
Hi @jeanlouisboudart - you're a member of [@highway-to-urhell](https://github.com/highway-to-urhell)'s organisation on GitHub, but our audit-bot has noticed your GitHub account isn't fully set up to meet the standards we need.

If you're no longer supposed to be a member of the organisation, please use your [GitHub organisation settings](https://github.com/settings/organizations) page to leave.

Otherwise, we just need you to help us with a few things to keep our code safe and secure on GitHub:

* Enable [two-factor authentication](https://help.github.com/articles/about-two-factor-authentication) in your [GitHub account settings](https://github.com/settings/admin).

Thanks for helping us out - it makes our lives a lot easier, and help keeps our code secure!

**Comment by nicopoirier** [comment]
test git who
